### ISSUE TITLE
Show error message if python version does not match

### ISSUE THREAD

**Issue by miho** [UG4/ughub#2]
Show an error message like `"Unsupported Version Of Python: 3.X"` before causing errors that lead to undefined behavior.

**Comment by sreiter** [comment]
Thanks for pointing it out and providing an example!

**Comment by miho** [comment]
Seems to work great now. Feel free to reopen this issue if necessary.

**Comment by sreiter** [comment]
I removed the error check and instead improved Python 3 compatibility of the code. From now on ughub should work both for Python 2 and Python 3..
