### ISSUE TITLE
Line 454 in ughub.py break ughub with Python 2.x 

### ISSUE THREAD

**Issue by stephanmg** [UG4/ughub#20]
See the line 454 in `ughub.py` for the problem: https://github.com/UG4/ughub/blob/0a7d9fbcd3c1cd391585f96606c569b9754ecb11/ughub.py#L454

> ughub requires Python to run (at least version 2.6 should be available, higher is recommended). Please make sure that python is installed by executing the following command (Mac-OSX, Linux):

The print() function inserts a new line at the end, by default. In Python 2, it can be suppressed by putting ',' at the end. In Python 3, "end =' '" appends space instead of newline.

Line 454 of `ughub.py` uses the latter (Python 3 only) syntax which will break `ughub` when using with Python 2.x.
I would suggest to either state if Python 2.x is still supported in the `README.md` or change this line. (As I scanned through `ughub.py` it seems the only instance of this would be in line 454 and thus would be easy to change obviously).

**Comment by sreiter** [comment]
Thanks for reporting and investigating the problem. I think we should not abondon Python 2.x without a good reason. This seems like a solvable issue.
I think this issue has been introduced recently.

**Comment by sreiter** [comment]
@timsschoen I think this is related to your recent introduction of autocompletion. Maybe you have time to look into the issue. If not, please reassign the issue to me.
Thanks!

**Comment by stephanmg** [comment]
I would also be willing to fix this trivial issue. There are at least three obvious ways to resolve this problem. For now I just migrated all my CI setups (Travis/AppVeyor) to Python 3.x, so for me at least no issue of priority.

**Comment by timsschoen** [comment]
PR #21 should fix this issue.
