### ISSUE TITLE
lack of "removesource" command

### ISSUE THREAD

**Issue by marscher** [UG4/ughub#4]
If one can add a source, why not support a remove command?

**Comment by sreiter** [comment]
Thanks for your comment. Some commands were not yet implemented simply due to a lack of time. stephanmg reacted to this issue in #6. I suggest we'll continue discussion there.
Regards,
Sebastian

**Comment by sreiter** [comment]
Didn't want to close the request without you having the opportunity to comment.

**Comment by marscher** [comment]
Thats ok. One can, by the way, close issues via PRs. To do so, just write something like "Fixes #x" in a commit message.

**Comment by stephanmg** [comment]
Still needs to be merged to master see #12
