### ISSUE TITLE
Consider providing a PyPI package

### ISSUE THREAD

**Issue by marscher** [UG4/ughub#5]
Rationale is that one could install ughub with pip, the standard python package manager. This way it is very easy avoid the hassle of setting up a PATH, because distutils will take care of this during the installation process.

Since this package is pure Python it should be relatively easy (just provide a setup.py script and deploy a source pkg via python setup.py sdist upload).

**Comment by sreiter** [comment]
This sounds interesting, indeed! Will have a look at it.

**Comment by marscher** [comment]
I have implemented this on a branch, however it does not yet work with Python3.4. Shall we set up a simple travis testing before you start pulling in broken codes?
